# Définition du pipeline CI/CD
stages:
  - clone
  - publish

build:
  stage: clone
  image: maven:latest
  script:
    - echo "Clonage du dépôt..."
    - git clone $CI_REPOSITORY_URL
    - cd app-management

publish:
  stage: publish
  image: maven:latest
  script:
    - echo "Publication sur Docker Hub..."
    - mvn -B spring-boot:build-image -Dspring-boot.build-image.publish=true \
      -Ddocker.user=$DOCKER_USERNAME -Ddocker.token=$DOCKER_PASSWORD \
      -DskipTests
  only:
    - main
