# Définition du pipeline CI/CD
stages:
  - build
  - deploy

# Configuration des jobs
build:
  stage: build
  image: maven:latest
  script:
    - echo "Construction du projet..."
    - mvn -B package -DskipTests
  artifacts:
    paths:
      - target/*.jar

deploy:
  stage: deploy
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375/
  before_script:
    - echo "Login to Docker Hub..."
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  script:
    - echo "Construction de l'image Docker..."
    - docker build -t $DOCKER_USERNAME/app-management .
    - echo "Pousser l'image Docker sur Docker Hub..."
    - docker push $DOCKER_USERNAME/app-management
  only:
    - main  # Exécutez uniquement pour les commits sur la branche principale
