# Définition du pipeline CI/CD push on docker hub with maven
stages:
  - build
  - test
  - deploy

services:
  - docker:19.03.12-dind

variables:
    MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
    MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"

build:
    stage: build
    script:
        - mvn -B clean package
        - mvn -B spring-boot:build-image -Dspring-boot.build-image.publish=true -DskipTests
    only:
        - main

test:
    stage: test
    script:
        - mvn -B test
    only:
        - main

deploy:
    stage: deploy
    script:
        - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        - docker push $DOCKER_USERNAME/app-management
    only:
        - main
