# Définition du pipeline CI/CD
stages:
  - build
  - test
  - publish

# Configuration des jobs
build:
  stage: build
  image: maven:latest
  script:
    - echo "Clonage du dépôt..."
    - git clone $CI_REPOSITORY_URL
    - cd app-management
    - echo "Construction du projet..."
    - mvn -B package

test:
  stage: test
  image: maven:latest
  script:
    - echo "Exécution des tests..."
    - mvn test

publish:
  stage: publish
  image: maven:latest
  script:
    - echo "Publication sur Docker Hub..."
    - mvn -B spring-boot:bgenerate-resources -Dspring-boot.generate-resources.publish=true \
      -Ddocker.user=$DOCKER_USERNAME -Ddocker.token=$DOCKER_PASSWORD \
      -DskipTests
  only:
    - main  # Exécutez uniquement pour les commits sur la branche principale
