# Définition du pipeline CI/CD
stages:
  - build

# Configuration des jobs
build:
  stage: build
  image: docker:latest
  before_script:
    - echo "Clonage du dépôt..."
    - git clone $CI_REPOSITORY_URL
    - cd app-management
  script:
    - echo "Construction avec Docker Compose..."
    - docker-compose build
    - echo "Connexion à Docker Hub..."
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - echo "Tag avec Docker Hub..."
    - docker tag app-management $DOCKER_USERNAME/app-management
    - echo "Publication sur Docker Hub..."
    - docker push $DOCKER_USERNAME/app-management
  only:
    - main
