version: '3.9'

services:
  app-management:
    image: app-management
    container_name: app-management
    ports:
      - "8080:8080"
    restart: unless-stopped
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      directoryDatas: /app/data/
